# from class: framework.memory.storage_memory:MetaConfig
autobiographical_memory_md: .autobiographical_memory.md
behavior_preference_md: .behavior_preference.md
current_session_id: e4f6a794-a132-406c-ae07-f86538a5c26f
max_tokens: -1
mood_base_md: .mood_base.md
personality_md: .personality.md
summary_memory_md: .summary_memory.md
turn_rounds: 10
