# from class: framework.memory.storage_memory:MetaConfig
autobiographical_memory_md: .autobiographical_memory.md
behavior_preference_md: .behavior_preference.md
current_session_id: 6dddf220-b79b-484c-9a50-062fd2a803e6
max_tokens: -1
mood_base_md: .mood_base.md
personality_md: .personality.md
summary_memory_md: .summary_memory.md
turn_rounds: 10
